### Create a 1D NumPy array with values from 0 to 9.

###  Create a 3x3 NumPy array of all zeros.

###  Create a 5x5 identity matrix.

###  Create a NumPy array of 10 random integers between 1 and 100.

###  Generate a 2D array (3x3) with random floats between 0 and 1.

###  Replace all odd numbers in a NumPy array with -1.

### Reverse a 1D NumPy array (e.g., [1, 2, 3] becomes [3, 2, 1]).

### Stack two 1D arrays vertically and horizontally.

### Create a 3x3 matrix and compute its mean, median, and standard deviation.

### Extract all elements from an array greater than a given value.

### Find the indices of non-zero elements in a NumPy array.

### Create a 10-element array and sort it.

### Check if two NumPy arrays are equal.

### Create a 4x4 matrix and calculate the sum of each column.

In [3]:
#Create a 1D NumPy array with values from 0 to 9.

import numpy as np

In [4]:
np.array([0,1,2,3,4,5,6,7,8,9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### OR

In [2]:
import numpy as np

arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [5]:
#Create a 3x3 NumPy array of all zeros.
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
#Create a 5x5 identity matrix.
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [7]:
# create a NumPy array of 10 random integers between 1 and 100.
arr = np.random.randint(1,100,10)
arr

array([66, 21, 53, 95, 23, 22, 85, 72,  7, 15], dtype=int32)

In [5]:
# Generate a 2D array (3x3) with random floats between 0 and 1.
b = np.random.random((3,2,3))
b

array([[[0.77329707, 0.28091745, 0.92096184],
        [0.75798171, 0.95145239, 0.78404168]],

       [[0.00788025, 0.39854136, 0.31391883],
        [0.02774976, 0.68911307, 0.21400236]],

       [[0.25133936, 0.97095141, 0.93889212],
        [0.33468841, 0.9530518 , 0.83794055]]])

In [9]:
#Replace all odd numbers in a NumPy array with -1.
c = np.array([1,2,3,4,5,6,7,8,9,10])
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
c = np.where(c%2 != 0, -1,c)
c

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [11]:
# Reverse a 1D NumPy array (e.g., [1, 2, 3] becomes [3, 2, 1]).
d = np.array([10,9,8,7,6,5,4,3,2,1])
d[::-1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
#Stack two 1D arrays vertically and horizontally.
e = np.array([1,2,3,4,5])
f = np.array([7,8,9,3,5])

In [13]:
e

array([1, 2, 3, 4, 5])

In [14]:
f

array([7, 8, 9, 3, 5])

In [15]:
j =np.vstack((e,f))
j

array([[1, 2, 3, 4, 5],
       [7, 8, 9, 3, 5]])

In [16]:
d = np.hstack((e,f))
d

array([1, 2, 3, 4, 5, 7, 8, 9, 3, 5])

# Create a 3x3 matrix and compute its mean, median, and standard deviation.

In [17]:
hi = np.random.randint(1,100,size = (3,3))
hi

array([[ 8, 90, 27],
       [86, 47, 12],
       [83, 14, 57]], dtype=int32)

In [18]:
np.mean(hi)

np.float64(47.111111111111114)

In [19]:
# Tp print Column Mean
np.mean(hi,axis=0)

array([59.        , 50.33333333, 32.        ])

In [20]:
np.mean(hi, axis=1)

array([41.66666667, 48.33333333, 51.33333333])

In [21]:
np.median(hi)

np.float64(47.0)

In [22]:
np.median(hi,axis= 0)

array([83., 47., 27.])

In [23]:
np.median(hi,axis=1)

array([27., 47., 57.])

In [24]:
np.std(hi)

np.float64(31.62433818172483)

### Extract all elements from an array greater than a given value.

In [25]:
arr1 = np.random.randint(2,100, 20)
arr1

array([85, 89,  4, 64, 46, 20, 79, 73, 52, 38, 77, 51, 51, 86, 31, 51, 70,
       41, 67, 97], dtype=int32)

In [26]:
arr1[arr1<50]

array([ 4, 46, 20, 38, 31, 41], dtype=int32)

In [27]:
# Find the indices of non-zero elements in a NumPy array.
arr2 = np.array([1,0,2,0,0,3,4,5,0,6,9])
arr2

array([1, 0, 2, 0, 0, 3, 4, 5, 0, 6, 9])

In [28]:
np.nonzero(arr) #shows index position

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),)

In [30]:
# Create a 10-element array and sort it.

arr3 = np.array([1,5,7,8,9,2,3,4,6,8,])
arr3

array([1, 5, 7, 8, 9, 2, 3, 4, 6, 8])

In [31]:
np.sort(arr3)

array([1, 2, 3, 4, 5, 6, 7, 8, 8, 9])

In [32]:
# Check if two NumPy arrays are equal.
arr1=([1,2,3,4])
arr2=([1,2,3,4])
hi=np.array_equal(arr1,arr2)
hi

True

In [33]:
#Create a 4x4 matrix and calculate the sum of each column.
arr1=np.random.randint(1,50,size=(4,4))
arr1

array([[39, 49, 44, 43],
       [37, 43, 24,  7],
       [24, 13, 43, 23],
       [15,  4,  4, 22]], dtype=int32)

In [34]:
np.sum(arr1,axis=0)

array([115, 109, 115,  95])