In [1]:
import numpy as np

# Concatenate

In [2]:
arr1 = np.random.randint(1,100,size = (3,3))
arr1

array([[65, 57, 26],
       [26, 85, 40],
       [28, 77, 52]], dtype=int32)

In [3]:
arr2 = np.random.randint(1,100,size = (3,3))
arr2

array([[42,  2, 65],
       [12, 72, 20],
       [92, 19, 21]], dtype=int32)

In [7]:
np.concatenate([arr1,arr2])

array([[65, 57, 26],
       [26, 85, 40],
       [28, 77, 52],
       [42,  2, 65],
       [12, 72, 20],
       [92, 19, 21]], dtype=int32)

#### To append column wise

In [ ]:
np.concatenate([arr1,arr2],axis=0)

array([[65, 57, 26, 42,  2, 65],
       [26, 85, 40, 12, 72, 20],
       [28, 77, 52, 92, 19, 21]], dtype=int32)

### To append RowWise

In [12]:
np.concatenate([arr1,arr2],axis = 1)

array([[65, 57, 26, 42,  2, 65],
       [26, 85, 40, 12, 72, 20],
       [28, 77, 52, 92, 19, 21]], dtype=int32)

# Transpose Matrix

### converts row into colum and column into row

In [21]:
arr = np.random.randint(1,100, size = (4,3))
arr

array([[42, 67, 33],
       [81, 96, 56],
       [55, 41, 22],
       [19, 40, 47]], dtype=int32)

### Matrix Multiplication

In [22]:
arr1 = np.random.randint(1,10,size = (2,2))
arr2 = np.random.randint (1,10,size = (2,2))

In [23]:
arr1

array([[7, 7],
       [5, 4]], dtype=int32)

In [24]:
arr2

array([[1, 3],
       [5, 2]], dtype=int32)

In [25]:
arr1*arr2

array([[ 7, 21],
       [25,  8]], dtype=int32)

### dot product

In [28]:
np.dot(arr1, arr2)

array([[42, 35],
       [25, 23]], dtype=int32)

## Diffrent functions in numpy 
### Where

In [30]:
## np.where (condition,'if condTrue','else 'condition')

arr2 = np.array([4,3,10,15,12,20,25,34,70])
arr2

array([ 4,  3, 10, 15, 12, 20, 25, 34, 70])

## To extract only even number 

In [31]:
np.where(arr2%2 == 0,"EVEN","ODD")

array(['EVEN', 'ODD', 'EVEN', 'ODD', 'EVEN', 'EVEN', 'ODD', 'EVEN',
       'EVEN'], dtype='<U4')

### Generate a random array and add the 10 for the even number of array

In [32]:
arr2

array([ 4,  3, 10, 15, 12, 20, 25, 34, 70])

In [34]:
np.where(arr2%2 == 0,arr2 + 10,arr2)

array([14,  3, 20, 15, 22, 30, 25, 44, 80])

#### Sort

In [35]:
np.sort(arr2)

array([ 3,  4, 10, 12, 15, 20, 25, 34, 70])

### For descending to ascending 
#### There is no reverse method we use indexing 

In [37]:
arr2

array([ 4,  3, 10, 15, 12, 20, 25, 34, 70])

In [39]:
arr2[::-1]

array([70, 34, 25, 20, 12, 15, 10,  3,  4])

#### np.delete()

In [41]:
np.delete(arr2,0)

array([ 3, 10, 15, 12, 20, 25, 34, 70])

In [42]:
arr2

array([ 4,  3, 10, 15, 12, 20, 25, 34, 70])

###### Array is static ,runtime ma change garna mildaina sp reassign garnu parney hunxa jailey as follows

In [ ]:
arr3= np.delete(arr2,0)

In [44]:
arr3

array([ 3, 10, 15, 12, 20, 25, 34, 70])

In [45]:
arr3

array([ 3, 10, 15, 12, 20, 25, 34, 70])

## np.insert()

In [48]:
np.insert(arr3,1,1000)

array([   3, 1000,   10,   15,   12,   20,   25,   34,   70])

In [49]:
arr3

array([ 3, 10, 15, 12, 20, 25, 34, 70])

In [51]:
arr4 = np.insert(arr3,1,1000)
arr4

array([   3, 1000,   10,   15,   12,   20,   25,   34,   70])

In [52]:
arr4

array([   3, 1000,   10,   15,   12,   20,   25,   34,   70])

#### put()-----> Replaces

In [53]:
np.put(arr4, [0,1],[100,200])

In [54]:
arr4

array([100, 200,  10,  15,  12,  20,  25,  34,  70])