In [13]:
! pip install numpy

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


## import library

In [2]:
import numpy as np

In [3]:
list = [ 10, 20, 30 ,40,50]

print(list)
print(type(list))

[10, 20, 30, 40, 50]
<class 'list'>


In [4]:
# convert list into array the array
arr = np.array(list)
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


# different attributes in numpy array (shape , size , dimensions)

In [5]:
arr

array([10, 20, 30, 40, 50])

In [6]:
arr.ndim # array.ndim  --- Gives types of Dimension of the array

1

In [7]:
# Size returns array ma katiota elements xa vanera return garxa
arr.size

5

In [8]:
arr.shape    # array shape of 5 in 1 direction (total number of rows and total number of column)

(5,)

## 2 dimension array (yesko lagi list vitra list dina parxa)

In [10]:
lst2 = [[10,20,30],[40,50,60],[70,80,90]]

In [12]:
lst2[2]

[70, 80, 90]

In [13]:
lst2[1]

[40, 50, 60]

In [15]:
lst2[0]

[10, 20, 30]

In [18]:
# to convert array 
arr2d = np.array(lst2)

In [19]:
arr2d.ndim

2

In [20]:
arr2d.shape #Gives matrix data type

(3, 3)

In [21]:
#list is hetregenous [1,2.5."ram",True]
#But array is homogenous [10,20,30], [10.2,11.2,4.5]

In [22]:
arr2d.size

9

# 3 dimension array

In [34]:
lst31 =[ [10,20,30,12],[50,60,70,80],[90,100,120,140] ]
lst32 =[ [100,200,300,120],[500,600,700,800],[900,1000,1200,1400] ]

In [35]:
lst33 = [lst31, lst32]
lst33[0]

[[10, 20, 30, 12], [50, 60, 70, 80], [90, 100, 120, 140]]

In [36]:
#To convert into 3 dimension 
arr3d = np.array(lst33)
arr3d

array([[[  10,   20,   30,   12],
        [  50,   60,   70,   80],
        [  90,  100,  120,  140]],

       [[ 100,  200,  300,  120],
        [ 500,  600,  700,  800],
        [ 900, 1000, 1200, 1400]]])

In [37]:
arr3d.shape

(2, 3, 4)

In [38]:
# 2 ley total hamro 2 ta 3 ota dimension vako array xa vanxa
# 3,4 ley 3*4  3 ta row ra 4 ta column represent garxa

In [39]:
arr3d.ndim

3

In [40]:
arr3d.size   # (3*4)--->12 + 12

24

# Data types

# Float into integer

In [41]:
data = [10.55,10.66,3.7,9.0,5.8]
np.array(data)

array([10.55, 10.66,  3.7 ,  9.  ,  5.8 ])

In [45]:
#To convert this data type into integer
np.array (data,dtype = int )

array([10, 10,  3,  9,  5])

# Integer into float

In [51]:
lst2 = [12,13,14,15]
np.array(lst2,dtype = 'float')

array([12., 13., 14., 15.])

# Boolean ()True of false --> everything except 0 is True

In [53]:
lst = [10,20,30,-10,100,0,23,0]

np.array(lst, dtype = bool)

array([ True,  True,  True,  True,  True, False,  True, False])

## Random number generation for 1d ,2d,3d, special function (Zeros,ones,identity)

## 0 to 1 range 

In [3]:
import numpy as np

In [4]:
arr = np.random.random(6) #----->6 is the total number 
arr #by default output is given in float #range in between 0 and 1

array([0.29577282, 0.70839639, 0.15322946, 0.38951455, 0.66114081,
       0.63756888])

In [5]:
np.random.random((2,3)) #--->Gives two rows and three column array

array([[0.19509772, 0.78792019, 0.75939747],
       [0.10494061, 0.29759256, 0.44909947]])

In [6]:
np.random.random((3,3,4))  #___>first three gives dimension and another 3 is row and 4 is column

array([[[0.22005443, 0.70085515, 0.19588159, 0.29978888],
        [0.22522728, 0.74295133, 0.83393512, 0.44212696],
        [0.32373147, 0.17075115, 0.54158115, 0.9536068 ]],

       [[0.49870523, 0.52991793, 0.80007558, 0.53567219],
        [0.17350922, 0.07699314, 0.94923684, 0.36780297],
        [0.15811547, 0.20416427, 0.96210805, 0.68490452]],

       [[0.40268066, 0.26216896, 0.41095984, 0.53341035],
        [0.4375907 , 0.3990195 , 0.53316954, 0.3068443 ],
        [0.57929229, 0.4203902 , 0.04661103, 0.91197779]]])

## Now if we want to give range ourselves.
## 50 to 80

In [10]:
np.random.randint(50, 80, 5)    #--->50 and 80 is range and 5 is total number of elements for 1 dimension

array([72, 64, 66, 73, 72], dtype=int32)

In [11]:
np.random.randint(90,100, size = (2,3,3))   #this is three dimension.

array([[[98, 93, 97],
        [95, 98, 98],
        [92, 92, 92]],

       [[95, 95, 90],
        [99, 97, 97],
        [95, 96, 98]]], dtype=int32)

# special function in numpy (Zeros,,ones , identity)

In [14]:
np.zeros(10,dtype = int) #gives 10 zeros number

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((4,3), dtype = bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [25]:
np.zeros((3,3,3),dtype=int) #--> # dimension 3 rows and 3 column

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [26]:
np.zeros ((2,2),dtype = bool )

array([[False, False],
       [False, False]])

# ones

In [27]:
np.ones((2,2), dtype = bool )

array([[ True,  True],
       [ True,  True]])

# identity

In [28]:
np.identity (2, dtype = bool)

array([[ True, False],
       [False,  True]])

In [29]:
np.identity ((5),dtype = int )

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Different arithematic operators

In [32]:
arr1 = np.random.randint (40,60,size = (2,2))
arr2 = np.random.randint (40,60,size = (2,2))
arr1

array([[59, 41],
       [57, 56]], dtype=int32)

In [33]:
arr2

array([[42, 50],
       [47, 51]], dtype=int32)

In [34]:
arr1 + arr2

array([[101,  91],
       [104, 107]], dtype=int32)

In [35]:
arr1 - arr2

array([[17, -9],
       [10,  5]], dtype=int32)

In [36]:
arr1 * arr2

array([[2478, 2050],
       [2679, 2856]], dtype=int32)

## Real examples practice

## Convert degree celcius into feranite .

In [39]:
temp_in_degree = np.array([12,20,0,0,0])
#degree to F formula : 0 degree celcius * 9/5)+ 32 = 32 degree F
temp_in_f = temp_in_degree * (9/5) + 32
temp_in_f


array([53.6, 68. , 32. , 32. , 32. ])

# Increase the salary of every employee by 10 %

In [40]:
salary = np.array([10000,20000,30000])
salary

array([10000, 20000, 30000])

In [42]:
salary_after_increase = salary * 1.1
salary_after_increase

array([11000., 22000., 33000.])

# Discount the price of every item by 20%

In [46]:
sales_data = np.array([10000,20000,30000])
after_discount = sales_data * 0.8
after_discount

array([ 8000., 16000., 24000.])